// export const UPDATE_STORE = 'UPDATE_STORE';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_PROMOTIONS = 'UPDATE_PROMOTIONS';
export const UPDATE_KEYWORDS = 'UPDATE_KEYWORDS';

// ALL STAY
export const OPEN_ITEM_DETAIL = 'OPEN_ITEM_DETAIL';
export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES';
export const LOAD_GLOBAL_STATE = 'LOAD_GLOBAL_STATE';
export const UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';


// EXPPORT CONST UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const TOGGLE_CART = 'TOGGLE_CART';

