import Joi from "joi";

export const generalScalarsValidation = {
    AuthorizationInput: Joi.object({
        token: Joi.string(),
        role: Joi.string(),
        isAuthentic: Joi.boolean(),
    }),
    PaginationInput: Joi.object({
        page: Joi.number(),
        limit: Joi.number(),
    }),
    SortInput: Joi.object({
        field: Joi.string(),
        order: Joi.number(),
    }),
    UpdateInput: Joi.object({
        field: Joi.string(),
        value: Joi.string(),
    }),
    batchUpdateInput: Joi.object({
        id: Joi.string(),
        updates: Joi.array().items(Joi.link(UpdateInput)),
    }),
    NestedUpdateInput: Joi.object({
        field: Joi.string(),
        value: Joi.string(),
        subFields: Joi.array().items(Joi.link(NestedUpdateInput)),
    }),
    dataInput: Joi.object({
        key: Joi.string(),
        value: Joi.string(),
    }),
    payloadsInput: Joi.object({
        entity: Joi.string(),
        data: Joi.array().items(Joi.link(dataInput)),
        id: Joi.string(),
    }),
    queryInput: Joi.object({
        field: Joi.string(),
    }),
};

// String: Joi.string(),
// Number: Joi.number(),
// Boolean: Joi.boolean(),
// Date: Joi.date(),
// Array: Joi.array(),
// Object: Joi.object(),
// StringRequired: Joi.string().required(),
// NumberRequired: Joi.number().required(),
// BooleanRequired: Joi.boolean().required(),
// DateRequired: Joi.date().required(),
// ArrayRequired: Joi.array().required(),
// ObjectRequired: Joi.object().required(),
// StringMin3Max50: Joi.string().min(3).max(50),
// NumberMin3Max50: Joi.number().min(3).max(50),
// BooleanMin3Max50: Joi.boolean().min(3).max(50),
// DateMin3Max50: Joi.date().min(3).max(50),
// ArrayMin3Max50: Joi.array().min(3).max(50),
// ObjectMin3Max50: Joi.object().min(3).max(50),
// StringMin3: Joi.string().min(3),
// NumberMin3: Joi.number().min(3),
// BooleanMin3: Joi.boolean().min(3),
// DateMin3: Joi.date().min(3),
// ArrayMin3: Joi.array().min(3),
// ObjectMin3: Joi.object().min(3),
// StringMax50: Joi.string().max(50),
// NumberMax50: Joi.number().max(50),
// BooleanMax50: Joi.boolean().max(50),
// DateMax50: Joi.date().max(50),
// ArrayMax50: Joi.array().max(50),
// ObjectMax50: Joi.object().max(50),
// StringEmail: Joi.string().email(),
// NumberEmail: Joi.number().email(),
// BooleanEmail: Joi.boolean().email(),
// DateEmail: Joi.date().email(),
// ArrayEmail: Joi.array().email(),
// ObjectEmail: Joi.object().email(),
// StringMin3Max50Email: Joi.string().min(3).max(50).email(),
// NumberMin3Max50Email: Joi.number().min(3).max(50).email(),
// BooleanMin3Max50Email: Joi.boolean().min(3).max(50).email(),
