import Joi from 'joi';

export const productValidation = {
    ProductInput: Joi.object({
        name: Joi.string().min(3).max(50).required(),
        quickDescription: Joi.string().min(3).max(500).required(),
        description: Joi.string().min(3).max(2000).required(),
        descriptionImages: Joi.array().items(Joi.string()),
        primaryColors: Joi.array().items(Joi.string()),
        secondaryColors: Joi.array().items(Joi.string()),
        category: Joi.string().min(3).max(50).required(),
        season: Joi.string().min(3).max(50).required(),
        promotions: Joi.array().items(Joi.string()),
        keywords: Joi.array().items(Joi.string()),
        featured: Joi.boolean(),
        recommendationId: Joi.string().min(3).max(50).required(),
        reviews: Joi.array().items(Joi.string()),
        rating: Joi.number().min(1).max(5),
        makeYourOwn: Joi.boolean(),
        price: Joi.number().required(),
        discount: Joi.number(),
        taxCategory: Joi.string().min(3).max(50).required(),
        includes: Joi.array().items(Joi.string()),
        bundle: Joi.boolean(),
        bundled: Joi.boolean(),
        image: Joi.string().required(),
        quantity: Joi.number().required(),
        weight: Joi.number().required(),
        dimensions: Joi.object({
            length: Joi.number(),
            width: Joi.number(),
            height: Joi.number(),
            size: Joi.string(),
        }),
        userInteraction: Joi.object({
            lovedCount: Joi.number(),
            cartCount: Joi.number(),
            wishlistCount: Joi.number(),
            viewedCount: Joi.number(),
        }),
        createdAt: Joi.date().required(),
        updatedAt: Joi.date(),
        images: Joi.array().items(Joi.object({
            image: Joi.string(),
            index: Joi.number(),
        })),
        colors: Joi.array().items(Joi.object({
            color: Joi.string(),
            index: Joi.number(),
        })),
        ownerId: Joi.string(),
    }),
    DimensionsInput: Joi.object({
        length: Joi.number(),
        width: Joi.number(),
        height: Joi.number(),
        size: Joi.string(),
    }),
    UserInteractionInput: Joi.object({
        lovedCount: Joi.number(),
        cartCount: Joi.number(),
        wishlistCount: Joi.number(),
        viewedCount: Joi.number(),
    }),
};